# Kibana %%KIBANA_VERSION%%

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM %%UPSTREAM_IMAGE_DIGEST%%

# The upstream image was built by:
#   https://github.com/elastic/kibana-docker/tree/%%KIBANA_VERSION%%

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/kibana/reference/current/docker.html

# See https://github.com/docker-library/official-images/pull/4917 for more details.
