# Kibana 7.17.11

# This image re-bundles the Docker image from the upstream provider, Elastic.
FROM docker.elastic.co/kibana/kibana:7.17.11@sha256:c18221ec6c140acc9229c44e8fb85b0627b996c4cafd0adb06767a794541905d
# Supported Bashbrew Architectures: amd64 arm64v8

# The upstream image was built by:
#   https://github.com/elastic/dockerfiles/tree/v7.17.11/kibana

# The build can be reproduced locally via:
#   docker build 'https://github.com/elastic/dockerfiles.git#v7.17.11:kibana'

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For documentation visit https://www.elastic.co/guide/en/kibana/current/docker.html

# See https://github.com/docker-library/official-images/pull/4917 for more details.
