# Kibana 7.1.1

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/kibana/kibana:7.1.1@sha256:fbf558c6df18500f00ab9c1e1ce2d566ad2c1800d023106e4a4a85274b0d40cd

# The upstream image was built by:
#   https://github.com/elastic/dockerfiles/tree/v7.1.1/kibana

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For documentation visit https://www.elastic.co/guide/en/kibana/current/docker.html

# See https://github.com/docker-library/official-images/pull/4917 for more details.
