# Kibana 7.0.1

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/kibana/kibana:7.0.1@sha256:8dbefebec1a038013b21ca08fabcdca1fd34fe2176afe364ccaae05d49b6b845

# The upstream image was built by:
#   https://github.com/elastic/dockerfiles/tree/v7.0.1/kibana

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For documentation visit https://www.elastic.co/guide/en/kibana/current/docker.html

# See https://github.com/docker-library/official-images/pull/4917 for more details.
