# Kibana 6.5.0

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/kibana/kibana:6.5.0@sha256:390d043692e64bfbc85d3cd547e3ff85f80506bb225e021e28e3a28a2688cfc4

# The upstream image was built by:
#   https://github.com/elastic/kibana-docker/tree/6.5.0

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/kibana/reference/current/docker.html

# See https://github.com/docker-library/official-images/pull/4917 for more details.
