# Kibana 6.5.2

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/kibana/kibana:6.5.2@sha256:e7c0a8817550a5e6f0be27f29684f9e476279bf63e62c641ea53876c0a0cef3c

# The upstream image was built by:
#   https://github.com/elastic/kibana-docker/tree/6.5.2

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/kibana/reference/current/docker.html

# See https://github.com/docker-library/official-images/pull/4917 for more details.
