# Kibana 6.6.0

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/kibana/kibana:6.6.0@sha256:7c6eadb13667e36d21b7e96809a02d14527c15bbfc5b92631168a58ed5f9fd33

# The upstream image was built by:
#   https://github.com/elastic/kibana-docker/tree/6.6.0

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/kibana/reference/current/docker.html

# See https://github.com/docker-library/official-images/pull/4917 for more details.
