# Kibana 8.8.2

# This image re-bundles the Docker image from the upstream provider, Elastic.
FROM docker.elastic.co/kibana/kibana:8.8.2@sha256:f7d62957d7a831209e873bf99ded2c2f9cddcbde3acac3071fe42e318b6911af
# Supported Bashbrew Architectures: amd64 arm64v8

# The upstream image was built by:
#   https://github.com/elastic/dockerfiles/tree/v8.8.2/kibana

# The build can be reproduced locally via:
#   docker build 'https://github.com/elastic/dockerfiles.git#v8.8.2:kibana'

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For documentation visit https://www.elastic.co/guide/en/kibana/current/docker.html

# See https://github.com/docker-library/official-images/pull/4917 for more details.
