# Kibana 6.4.0

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/kibana/kibana:6.4.0@sha256:e61c1122d9bc8dc8a113c79a035cf3c34d09674685f550ec842afc2d923ad568

# The upstream image was built by:
#   https://github.com/elastic/kibana-docker/tree/6.4.0

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/kibana/reference/current/docker.html