# Kibana 6.4.1

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/kibana/kibana:6.4.1@sha256:e78521b699a843ae7c07d5d0e046b2822bc46470ae5de543216420443dd6ac39

# The upstream image was built by:
#   https://github.com/elastic/kibana-docker/tree/6.4.1

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/kibana/reference/current/docker.html

# See https://github.com/docker-library/official-images/pull/4917 for more details.
